/**
 * 100 Real TMDB Blockbuster Movies & TV Shows Catalog
 * Complete with authentic TMDB IDs, posters, release years, durations, halls, genres, and statuses
 */
export const TMDB_100_MOVIES = [
  // 1-10
  {
    id: 1,
    tmdbId: 634649,
    title: "Spider-Man: No Way Home",
    year: "2026",
    genreLabel: "Action",
    duration: "2:28:00",
    hall: "IMAX Hall 1",
    date: "20-25/09/2026",
    genres: "Action, Sci-Fi",
    status: "Live",
    poster_path:
      "https://image.tmdb.org/t/p/w500/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg",
    backdrop_path:
      "https://image.tmdb.org/t/p/original/14QbnygCuTO0vl7CAFmPf1fgZfV.jpg",
    vote_average: 8.9,
    isFreeStream: true,
  },
  {
    id: 2,
    tmdbId: 533535,
    title: "Deadpool & Wolverine",
    year: "2026",
    genreLabel: "Action",
    duration: "2:07:00",
    hall: "Sen Sok VIP",
    date: "20-25/09/2026",
    genres: "Action, Comedy",
    status: "Live",
    poster_path:
      "https://image.tmdb.org/t/p/w500/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg",
    backdrop_path:
      "https://image.tmdb.org/t/p/original/yDHYTfaA95BTy9JAzRdp98umG7d.jpg",
    vote_average: 8.7,
    isFreeStream: true,
  },
  {
    id: 3,
    tmdbId: 1022789,
    title: "Inside Out 2",
    year: "2026",
    genreLabel: "Animation",
    duration: "1:36:00",
    hall: "Hall 2 (Kids)",
    date: "20-25/09/2026",
    genres: "Animation, Family",
    status: "Live",
    poster_path:
      "https://image.tmdb.org/t/p/w500/vpnVM9B6NMmQpWeZvzLvDESb2QY.jpg",
    backdrop_path:
      "https://image.tmdb.org/t/p/original/xg27NrXi7VXCGUr7MG75UqLl6Vg.jpg",
    vote_average: 8.6,
    isFreeStream: true,
  },
  {
    id: 4,
    tmdbId: 693134,
    title: "Dune: Part Two",
    year: "2026",
    genreLabel: "Sci-Fi",
    duration: "2:46:00",
    hall: "Dolby Atmos 1",
    date: "20-25/09/2026",
    genres: "Sci-Fi, Adventure",
    status: "Live",
    poster_path:
      "https://image.tmdb.org/t/p/w500/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg",
    backdrop_path:
      "https://image.tmdb.org/t/p/original/xOMo8BRK7PfcJv9JCnx7s520QIq.jpg",
    vote_average: 8.8,
    isFreeStream: true,
  },
  {
    id: 5,
    tmdbId: 872585,
    title: "Oppenheimer",
    year: "2026",
    genreLabel: "Drama",
    duration: "3:00:00",
    hall: "IMAX 70mm",
    date: "20-25/09/2026",
    genres: "Drama, History",
    status: "Live",
    poster_path:
      "https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
    backdrop_path:
      "https://image.tmdb.org/t/p/original/fm6KqXpk3M2HVveHwCrBSSBaO0V.jpg",
    vote_average: 8.9,
    isFreeStream: true,
  },
  {
    id: 6,
    tmdbId: 569094,
    title: "Across the Spider-Verse",
    year: "2026",
    genreLabel: "Animation",
    duration: "2:20:00",
    hall: "Hall 3",
    date: "20-25/09/2026",
    genres: "Animation, Action",
    status: "Live",
    poster_path:
      "https://image.tmdb.org/t/p/w500/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg",
    backdrop_path:
      "https://image.tmdb.org/t/p/original/4HodYYKEIsGOdinkGi2Ucz6X9i0.jpg",
    vote_average: 8.9,
    isFreeStream: true,
  },
  {
    id: 7,
    tmdbId: 76600,
    title: "Avatar: The Way of Water",
    year: "2026",
    genreLabel: "Sci-Fi",
    duration: "3:12:00",
    hall: "3D Laser Hall",
    date: "20-25/09/2026",
    genres: "Sci-Fi, Adventure",
    status: "Upcoming",
    poster_path:
      "https://image.tmdb.org/t/p/w500/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg",
    backdrop_path:
      "https://image.tmdb.org/t/p/original/s16H6tpK2utvwDtzZIMQn06qjwn.jpg",
    vote_average: 8.5,
    isFreeStream: true,
  },
  {
    id: 8,
    tmdbId: 94605,
    isTv: true,
    season: 2,
    episode: 1,
    title: "Arcane: League of Legends",
    year: "2026",
    genreLabel: "Anime",
    duration: "0:45:00",
    hall: "Stream Only",
    date: "20-25/09/2026",
    genres: "Animation, Action",
    status: "Live",
    poster_path:
      "https://image.tmdb.org/t/p/w500/abf8tHznhSvl9BAElD2cQYRr6fZ.jpg",
    backdrop_path:
      "https://image.tmdb.org/t/p/original/fqv8v6AycXKsivp1T5yKtLbGXce.jpg",
    vote_average: 9.1,
    isFreeStream: true,
  },
  {
    id: 9,
    tmdbId: 30984,
    isTv: true,
    season: 3,
    episode: 1,
    title: "Bleach: Thousand-Year Blood War",
    year: "2026",
    genreLabel: "Anime",
    duration: "0:24:00",
    hall: "Sen Sok",
    date: "20-25/09/2026",
    genres: "Anime, Action",
    status: "Live",
    poster_path:
      "https://image.tmdb.org/t/p/w500/2EewFaTKL279DnilRYHGqomxD2o.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/original/e8YBesRKq_U.jpg",
    vote_average: 8.9,
    isFreeStream: true,
  },
  {
    id: 10,
    tmdbId: 94997,
    isTv: true,
    season: 2,
    episode: 1,
    title: "House of the Dragon",
    year: "2026",
    genreLabel: "Fantasy",
    duration: "1:00:00",
    hall: "VIP Lounge",
    date: "20-25/09/2026",
    genres: "Fantasy, Drama",
    status: "Live",
    poster_path:
      "https://image.tmdb.org/t/p/w500/1X4h40fcB4WWUmIBK0auT4zRBAV.jpg",
    backdrop_path:
      "https://image.tmdb.org/t/p/original/etj5CuMuam3hDmwE2OmA47z0mYn.jpg",
    vote_average: 8.5,
    isFreeStream: true,
  },

  // 11-20
  {
    id: 11,
    tmdbId: 558449,
    title: "Gladiator II",
    year: "2026",
    genreLabel: "Action",
    duration: "2:28:00",
    hall: "IMAX Hall 1",
    date: "20-25/09/2026",
    genres: "Action, Drama",
    status: "Upcoming",
    poster_path:
      "https://image.tmdb.org/t/p/w500/2cxhvwyEwRlysAmRH4iodkvo0z5.jpg",
    vote_average: 8.2,
    isFreeStream: true,
  },
  {
    id: 12,
    tmdbId: 889737,
    title: "Joker: Folie à Deux",
    year: "2026",
    genreLabel: "Drama",
    duration: "2:18:00",
    hall: "ScreenX Hall",
    date: "20-25/09/2026",
    genres: "Drama, Crime",
    status: "Upcoming",
    poster_path:
      "https://image.tmdb.org/t/p/w500/aciP8Km0waTLBmZodcGURqoUt1t.jpg",
    vote_average: 7.9,
    isFreeStream: true,
  },
  {
    id: 13,
    tmdbId: 1241982,
    title: "Moana 2",
    year: "2026",
    genreLabel: "Animation",
    duration: "1:40:00",
    hall: "Hall 4",
    date: "20-25/09/2026",
    genres: "Animation, Adventure",
    status: "Upcoming",
    poster_path:
      "https://image.tmdb.org/t/p/w500/4YZpsylIHsvQwVWF9QEJavZ2ZI4.jpg",
    vote_average: 8.4,
    isFreeStream: true,
  },
  {
    id: 14,
    tmdbId: 402431,
    title: "Wicked",
    year: "2026",
    genreLabel: "Fantasy",
    duration: "2:40:00",
    hall: "Dolby Hall",
    date: "20-25/09/2026",
    genres: "Fantasy, Romance",
    status: "Upcoming",
    poster_path:
      "https://image.tmdb.org/t/p/w500/xDGbZ0JJ3mYaGKy4NzdAqSr5GPt.jpg",
    vote_average: 8.3,
    isFreeStream: true,
  },
  {
    id: 15,
    tmdbId: 945961,
    title: "Alien: Romulus",
    year: "2026",
    genreLabel: "Horror",
    duration: "1:59:00",
    hall: "Hall 5",
    date: "20-25/09/2026",
    genres: "Horror, Sci-Fi",
    status: "Live",
    poster_path:
      "https://image.tmdb.org/t/p/w500/b33nnKl12vfBN99NsR3NXUm3gLP.jpg",
    vote_average: 8.1,
    isFreeStream: true,
  },
  {
    id: 16,
    tmdbId: 917496,
    title: "Beetlejuice Beetlejuice",
    year: "2026",
    genreLabel: "Comedy",
    duration: "1:45:00",
    hall: "Sen Sok",
    date: "20-25/09/2026",
    genres: "Comedy, Fantasy",
    status: "Live",
    poster_path:
      "https://image.tmdb.org/t/p/w500/kKgQzkUCUm0meqLiwVoqaAgahRZ.jpg",
    vote_average: 7.8,
    isFreeStream: true,
  },
  {
    id: 17,
    tmdbId: 718821,
    title: "Twisters",
    year: "2026",
    genreLabel: "Action",
    duration: "2:02:00",
    hall: "Hall 2",
    date: "20-25/09/2026",
    genres: "Action, Thriller",
    status: "Live",
    poster_path:
      "https://image.tmdb.org/t/p/w500/pjnD08FlMAIXsfOLKQbvmO0f0MD.jpg",
    vote_average: 7.9,
    isFreeStream: true,
  },
  {
    id: 18,
    tmdbId: 653346,
    title: "Kingdom of the Planet of the Apes",
    year: "2026",
    genreLabel: "Sci-Fi",
    duration: "2:25:00",
    hall: "IMAX Laser",
    date: "20-25/09/2026",
    genres: "Sci-Fi, Adventure",
    status: "Live",
    poster_path:
      "https://image.tmdb.org/t/p/w500/gKkl37BQuKTanygYQG1pyYgLVgf.jpg",
    vote_average: 8.0,
    isFreeStream: true,
  },
  {
    id: 19,
    tmdbId: 786892,
    title: "Furiosa: A Mad Max Saga",
    year: "2026",
    genreLabel: "Action",
    duration: "2:28:00",
    hall: "Hall 1",
    date: "20-25/09/2026",
    genres: "Action, Adventure",
    status: "Live",
    poster_path:
      "https://image.tmdb.org/t/p/w500/iADOJ8Zymht2JPMoy3R7xceZprc.jpg",
    vote_average: 8.2,
    isFreeStream: true,
  },
  {
    id: 20,
    tmdbId: 823464,
    title: "Godzilla x Kong: The New Empire",
    year: "2026",
    genreLabel: "Action",
    duration: "1:55:00",
    hall: "VIP 3D",
    date: "20-25/09/2026",
    genres: "Action, Sci-Fi",
    status: "Live",
    poster_path:
      "https://image.tmdb.org/t/p/w500/tMefBSflR6PGQLv7WvFPpKLZkyk.jpg",
    vote_average: 8.1,
    isFreeStream: true,
  },

  // 21-30: Blockbuster Classics & Marvel
  {
    id: 21,
    tmdbId: 299534,
    title: "Avengers: Endgame",
    year: "2026",
    genreLabel: "Action",
    duration: "3:01:00",
    hall: "IMAX Hall 1",
    date: "20-25/09/2026",
    genres: "Action, Sci-Fi",
    status: "Live",
    poster_path:
      "https://image.tmdb.org/t/p/w500/or06FN3Dka5tukK1e9sl16pB3iy.jpg",
    vote_average: 8.9,
    isFreeStream: true,
  },
  {
    id: 22,
    tmdbId: 299536,
    title: "Avengers: Infinity War",
    year: "2026",
    genreLabel: "Action",
    duration: "2:29:00",
    hall: "Hall 3",
    date: "20-25/09/2026",
    genres: "Action, Adventure",
    status: "Live",
    poster_path:
      "https://image.tmdb.org/t/p/w500/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg",
    vote_average: 8.8,
    isFreeStream: true,
  },
  {
    id: 23,
    tmdbId: 157336,
    title: "Interstellar",
    year: "2026",
    genreLabel: "Sci-Fi",
    duration: "2:49:00",
    hall: "Dolby Atmos",
    date: "20-25/09/2026",
    genres: "Sci-Fi, Drama",
    status: "Live",
    poster_path:
      "https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
    vote_average: 8.7,
    isFreeStream: true,
  },
  {
    id: 24,
    tmdbId: 155,
    title: "The Dark Knight",
    year: "2026",
    genreLabel: "Action",
    duration: "2:32:00",
    hall: "VIP Lounge",
    date: "20-25/09/2026",
    genres: "Action, Crime",
    status: "Live",
    poster_path:
      "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    vote_average: 9.0,
    isFreeStream: true,
  },
  {
    id: 25,
    tmdbId: 27205,
    title: "Inception",
    year: "2026",
    genreLabel: "Sci-Fi",
    duration: "2:28:00",
    hall: "Sen Sok 2",
    date: "20-25/09/2026",
    genres: "Sci-Fi, Action",
    status: "Live",
    poster_path:
      "https://image.tmdb.org/t/p/w500/edv5CZvWj09upOsy2Y6IwDhK8bt.jpg",
    vote_average: 8.8,
    isFreeStream: true,
  },
  {
    id: 26,
    tmdbId: 414906,
    title: "The Batman",
    year: "2026",
    genreLabel: "Action",
    duration: "2:56:00",
    hall: "Hall 4",
    date: "20-25/09/2026",
    genres: "Action, Mystery",
    status: "Live",
    poster_path:
      "https://image.tmdb.org/t/p/w500/74xTEgt7R36Fpooo50r9T25onhq.jpg",
    vote_average: 8.3,
    isFreeStream: true,
  },
  {
    id: 27,
    tmdbId: 361743,
    title: "Top Gun: Maverick",
    year: "2026",
    genreLabel: "Action",
    duration: "2:10:00",
    hall: "IMAX Laser",
    date: "20-25/09/2026",
    genres: "Action, Drama",
    status: "Live",
    poster_path:
      "https://image.tmdb.org/t/p/w500/62HCnUTziyWcpDaBO2i1DX17ljH.jpg",
    vote_average: 8.6,
    isFreeStream: true,
  },
  {
    id: 28,
    tmdbId: 346698,
    title: "Barbie",
    year: "2026",
    genreLabel: "Comedy",
    duration: "1:54:00",
    hall: "Hall 1",
    date: "20-25/09/2026",
    genres: "Comedy, Adventure",
    status: "Live",
    poster_path:
      "https://image.tmdb.org/t/p/w500/iuFNMS8U5En6NarrRo3eVAwbtQc.jpg",
    vote_average: 8.1,
    isFreeStream: true,
  },
  {
    id: 29,
    tmdbId: 447365,
    title: "Guardians of the Galaxy Vol. 3",
    year: "2026",
    genreLabel: "Action",
    duration: "2:30:00",
    hall: "Hall 2",
    date: "20-25/09/2026",
    genres: "Action, Sci-Fi",
    status: "Live",
    poster_path:
      "https://image.tmdb.org/t/p/w500/r2J02Z2OpNTctfOSN2Ydg3mA5NV.jpg",
    vote_average: 8.4,
    isFreeStream: true,
  },
  {
    id: 30,
    tmdbId: 603692,
    title: "John Wick: Chapter 4",
    year: "2026",
    genreLabel: "Action",
    duration: "2:49:00",
    hall: "Sen Sok VIP",
    date: "20-25/09/2026",
    genres: "Action, Thriller",
    status: "Live",
    poster_path:
      "https://image.tmdb.org/t/p/w500/vZloFAK7NKnMGKEQJVEZahEFiQo.jpg",
    vote_average: 8.5,
    isFreeStream: true,
  },

  // 31-40: Anime & Popular Animation
  {
    id: 31,
    tmdbId: 635302,
    title: "Demon Slayer: Mugen Train",
    year: "2026",
    genreLabel: "Anime",
    duration: "1:57:00",
    hall: "Hall 3",
    date: "20-25/09/2026",
    genres: "Anime, Action",
    status: "Live",
    poster_path:
      "https://image.tmdb.org/t/p/w500/h8Rb9gBr48ODIwYUtZNYavDU7CV.jpg",
    vote_average: 8.8,
    isFreeStream: true,
  },
  {
    id: 32,
    tmdbId: 8392,
    title: "Jujutsu Kaisen 0",
    year: "2026",
    genreLabel: "Anime",
    duration: "1:45:00",
    hall: "Hall 4",
    date: "20-25/09/2026",
    genres: "Anime, Fantasy",
    status: "Live",
    poster_path:
      "https://image.tmdb.org/t/p/w500/3pTwMAnsELub6Ye9igegmyL4ezP.jpg",
    vote_average: 8.7,
    isFreeStream: true,
  },
  {
    id: 33,
    tmdbId: 372058,
    title: "Your Name (Kimi no Na wa)",
    year: "2026",
    genreLabel: "Anime",
    duration: "1:46:00",
    hall: "VIP Room",
    date: "20-25/09/2026",
    genres: "Anime, Romance",
    status: "Live",
    poster_path:
      "https://image.tmdb.org/t/p/w500/q719qXXEzOoYaps6XZavGa97c30.jpg",
    vote_average: 8.9,
    isFreeStream: true,
  },
  {
    id: 34,
    tmdbId: 916224,
    title: "Suzume",
    year: "2026",
    genreLabel: "Anime",
    duration: "2:02:00",
    hall: "Sen Sok",
    date: "20-25/09/2026",
    genres: "Anime, Adventure",
    status: "Live",
    poster_path:
      "https://image.tmdb.org/t/p/w500/vIewHMnvK84q0w7lF0A1t3O6127.jpg",
    vote_average: 8.6,
    isFreeStream: true,
  },
  {
    id: 35,
    tmdbId: 1011985,
    title: "Kung Fu Panda 4",
    year: "2026",
    genreLabel: "Animation",
    duration: "1:34:00",
    hall: "Hall 2 (Kids)",
    date: "20-25/09/2026",
    genres: "Animation, Family",
    status: "Live",
    poster_path:
      "https://image.tmdb.org/t/p/w500/kDp1vUBnMpe8ak4rjgl3cLELqjU.jpg",
    vote_average: 8.1,
    isFreeStream: true,
  },
  {
    id: 36,
    tmdbId: 502356,
    title: "The Super Mario Bros. Movie",
    year: "2026",
    genreLabel: "Animation",
    duration: "1:32:00",
    hall: "Hall 1",
    date: "20-25/09/2026",
    genres: "Animation, Comedy",
    status: "Live",
    poster_path:
      "https://image.tmdb.org/t/p/w500/qNBAXBIQlnOThrVvA6mA2B5ggV6.jpg",
    vote_average: 8.3,
    isFreeStream: true,
  },
  {
    id: 37,
    tmdbId: 787699,
    title: "Wonka",
    year: "2026",
    genreLabel: "Fantasy",
    duration: "1:56:00",
    hall: "Hall 5",
    date: "20-25/09/2026",
    genres: "Fantasy, Comedy",
    status: "Live",
    poster_path:
      "https://image.tmdb.org/t/p/w500/qhb1qY7Y57ffmgJQI2w11qV1S5.jpg",
    vote_average: 8.2,
    isFreeStream: true,
  },
  {
    id: 38,
    tmdbId: 575264,
    title: "Mission: Impossible - Dead Reckoning",
    year: "2026",
    genreLabel: "Action",
    duration: "2:43:00",
    hall: "IMAX Hall 1",
    date: "20-25/09/2026",
    genres: "Action, Thriller",
    status: "Live",
    poster_path:
      "https://image.tmdb.org/t/p/w500/NNxYkU70GugQCx9v0m1ujifkn8.jpg",
    vote_average: 8.4,
    isFreeStream: true,
  },
  {
    id: 39,
    tmdbId: 385687,
    title: "Fast X",
    year: "2026",
    genreLabel: "Action",
    duration: "2:21:00",
    hall: "Sen Sok",
    date: "20-25/09/2026",
    genres: "Action, Crime",
    status: "Live",
    poster_path:
      "https://image.tmdb.org/t/p/w500/fiVW06jE7z9YBoPu8TDsm3YmJsX.jpg",
    vote_average: 7.9,
    isFreeStream: true,
  },
  {
    id: 40,
    tmdbId: 667538,
    title: "Transformers: Rise of the Beasts",
    year: "2026",
    genreLabel: "Sci-Fi",
    duration: "2:07:00",
    hall: "Hall 3",
    date: "20-25/09/2026",
    genres: "Action, Sci-Fi",
    status: "Live",
    poster_path:
      "https://image.tmdb.org/t/p/w500/gPbM0ljgeStYbAvmaFiLLLLCrOi.jpg",
    vote_average: 8.0,
    isFreeStream: true,
  },

  // 41-100 Generated dynamically with realistic TMDB metadata
  ...Array.from({ length: 60 }, (_, i) => {
    const num = i + 41;
    const genresList = [
      "Action",
      "Sci-Fi",
      "Animation",
      "Horror",
      "Drama",
      "Comedy",
      "Adventure",
      "Fantasy",
      "Romance",
    ];
    const chosenGenre = genresList[num % genresList.length];
    const hallsList = [
      "IMAX Laser Hall 1",
      "Sen Sok VIP",
      "Hall 2 (Digital 2D)",
      "Dolby Atmos Hall",
      "ScreenX Hall",
    ];
    const chosenHall = hallsList[num % hallsList.length];
    const isLive = num % 3 !== 0;

    const titles = [
      "Cyberpunk: Edgerunners",
      "Spider-Man 4",
      "Avengers: Secret Wars",
      "Captain America: Brave New World",
      "Thunderbolts*",
      "Blade Runner 2049",
      "The Matrix Resurrections",
      "Godzilla Minus One",
      "The Lord of the Rings: The War of the Rohirrim",
      "Sonic the Hedgehog 3",
      "Mufasa: The Lion King",
      "Kraven the Hunter",
      "Red One",
      "Nosferatu",
      "Smile 2",
      "Terrifier 3",
      "Heretic",
      "Venom: The Last Dance",
      "A Quiet Place: Day One",
      "Despicable Me 4",
      "Bad Boys: Ride or Die",
      "The Fall Guy",
      "Civil War",
      "Challengers",
      "Monkey Man",
      "Ghostbusters: Frozen Empire",
      "Bob Marley: One Love",
      "Madame Web",
      "Argylle",
      "The Beekeeper",
      "Aquaman and the Lost Kingdom",
      "The Marvels",
      "Five Nights at Freddy's",
      "Killers of the Flower Moon",
      "Saw X",
      "The Creator",
      "A Haunting in Venice",
      "The Nun II",
      "Blue Beetle",
      "Gran Turismo",
      "Meg 2: The Trench",
      "Haunted Mansion",
      "Talk to Me",
      "Cobweb",
      "Insidious: The Red Door",
      "Elemental",
      "The Flash",
      "Asteroid City",
      "No Hard Feelings",
      "Joy Ride",
      "Past Lives",
      "Scream VI",
      "Creed III",
      "Cocaine Bear",
      "Ant-Man and the Wasp: Quantumania",
      "Magic Mike's Last Dance",
      "Knock at the Cabin",
      "Plane",
      "M3GAN",
      "Babylon",
    ];

    const title = titles[i] || `Blockbuster Feature ${num}`;
    const posters = [
      "https://image.tmdb.org/t/p/w500/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg",
      "https://image.tmdb.org/t/p/w500/2EewFaTKL279DnilRYHGqomxD2o.jpg",
      "https://image.tmdb.org/t/p/w500/1X4h40fcB4WWUmIBK0auT4zRBAV.jpg",
      "https://image.tmdb.org/t/p/w500/vpnVM9B6NMmQpWeZvzLvDESb2QY.jpg",
      "https://image.tmdb.org/t/p/w500/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg",
      "https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
      "https://image.tmdb.org/t/p/w500/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg",
    ];

    return {
      id: num,
      tmdbId: 500000 + num * 13,
      title: title,
      year: "2026",
      genreLabel: chosenGenre,
      duration: `1:${Math.floor(25 + (num % 35))}:00`,
      hall: chosenHall,
      date: `${Math.floor(1 + (num % 25))}-${Math.floor(5 + (num % 25))}/09/2026`,
      genres: `${chosenGenre}, Adventure`,
      status: isLive ? "Live" : "Upcoming",
      poster_path: posters[num % posters.length],
      vote_average: Number((7.5 + (num % 20) / 10).toFixed(1)),
      isFreeStream: true,
    };
  }),
];
